# Generated by Django 5.2.1 on 2025-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teljesnev', models.CharField(max_length=255)),
                ('becenev', models.CharField(max_length=255)),
                ('szulinap', models.DateField()),
                ('nevnap', models.DateField()),
                ('ajandek', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ember',
                'verbose_name_plural': 'Emberek',
            },
        ),
    ]
